//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainFuckSharp.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrainFuckSharp.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Runtime.CompilerServices;
        ///
        ///namespace test
        ///{
        ///    [CompilerGenerated]
        ///    public static class Program
        ///    {
        ///        private static readonly byte[] Memory = new byte[4096];
        ///        private static int CellCounter = 0;
        ///
        ///        public static void Main(string[] args)
        ///        {
        ///            Memory[CellCounter] += 10;
        ///            MultiplyAdd(1, 7);
        ///            MultiplyAdd(2, 10);
        ///            MultiplyAdd(3, 3);
        ///            MultiplyAdd(4, 1);
        ///            CellCounter += 1;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Runtime.CompilerServices;
        ///
        ///namespace test
        ///{
        ///    [CompilerGenerated]
        ///    public static class Program
        ///    {
        ///        private static readonly byte[] Memory = new byte[4096];
        ///        private static int CellCounter = 0;
        ///
        ///        public static void Main(string[] args)
        ///        {
        ///            Console.Write((char)Memory[CellCounter]);
        ///            Memory[CellCounter]++;
        ///            while (Memory[CellCounter] != 0)
        ///            {
        ///                Console.Write((char)Memory[CellC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleProgram {
            get {
                return ResourceManager.GetString("SimpleProgram", resourceCulture);
            }
        }
    }
}
